export const motivationalQuotes = [
  { text: "Excellence is not a skill, it's an attitude.", author: "Ralph Marston" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Teamwork makes the dream work.", author: "John C. Maxwell" },
  { text: "Every accomplishment starts with the decision to try.", author: "Unknown" },
  { text: "Your attitude determines your direction.", author: "Unknown" },
  { text: "Small daily improvements lead to stunning results.", author: "Robin Sharma" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "The harder you work, the luckier you get.", author: "Gary Player" },
  { text: "Success doesn't come from what you do occasionally, but what you do consistently.", author: "Marie Forleo" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Do it with passion or not at all.", author: "Rosa Couchette Carey" },
  { text: "Your only limit is you.", author: "Unknown" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle Onassis" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Success is not final, failure is not fatal. It is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "We become what we repeatedly do.", author: "Sean Covey" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
  { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
  { text: "People who are crazy enough to think they can change the world are the ones who do.", author: "Rob Siltanen" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "Knowing is not enough; we must apply.", author: "Bruce Lee" },
  { text: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Henry Link" },
  { text: "Successful people are not gifted; they just work hard, then succeed on purpose.", author: "G.K. Nielson" },
  { text: "Goal setting is the secret to a compelling future.", author: "Tony Robbins" },
  { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
  { text: "I've missed more than 9,000 shots in my career. I've lost almost 300 games. I've failed over and over. That is why I succeed.", author: "Michael Jordan" },
  { text: "The most difficult thing is the decision to act; the rest is merely tenacity.", author: "Amelia Earhart" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
  { text: "We must believe that we are gifted for something, and that this thing must be attained.", author: "Marie Curie" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "There's no telling how many miles you will have to run while chasing a dream.", author: "Anonymous" },
  { text: "It's not about ideas. It's about making ideas happen.", author: "Scott Belsky" },
  { text: "Never give in except to conviction of honor and good sense.", author: "Winston Churchill" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
  { text: "Coming together is a beginning. Keeping together is progress. Working together is success.", author: "Henry Ford" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "If everyone is moving forward together, then success takes care of itself.", author: "Henry Ford" },
  { text: "None of us is as smart as all of us.", author: "Ken Blanchard" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan" },
  { text: "Great things in business are never done by one person; they're done by a team.", author: "Steve Jobs" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "It is literally true that you can succeed best and quickest by helping others succeed.", author: "Napoleon Hill" },
  { text: "No one can whistle a symphony. It takes a whole orchestra to play it.", author: "H.E. Luccock" },
  { text: "Unity is strength; division is weakness.", author: "Swahili Proverb" },
  { text: "A single arrow is easily broken, but not ten in a bundle.", author: "Japanese Proverb" },
  { text: "Many hands make light work.", author: "John Heywood" },
  { text: "Excellence is doing ordinary things extraordinarily well.", author: "John W. Gardner" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "The pleasure we derive from doing favors is not so great as that of having others do them for us.", author: "Jean de la Bruyère" },
  { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "The customer's perception is your reality.", author: "Kate Zabriskie" },
  { text: "Make a customer, not a sale.", author: "Katherine Barchetti" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "Treat each customer as if they sign your paycheck, because they do.", author: "Walmart Customer Service Policy" },
  { text: "People will forget what you said, but they will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "Courteous treatment will make a customer a walking advertisement.", author: "James Cash Penney" },
  { text: "Cleanliness is not next to godliness, it is godliness.", author: "Mahatma Gandhi" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Order and simplification are the first steps toward mastery of a subject.", author: "Thomas Mann" },
  { text: "A place for everything, and everything in its place.", author: "Benjamin Franklin" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Punctuality is the politeness of kings.", author: "Louis XVIII" },
  { text: "Time is what we want most, but what we use worst.", author: "William Penn" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "Until we can manage time, we can manage nothing else.", author: "Peter Drucker" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { text: "Through perseverance many people win success out of what seemed destined to be certain failure.", author: "Benjamin Disraeli" },
  { text: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
  { text: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Step by step and the thing is done.", author: "Charles Atlas" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", author: "Theodore N. Vail" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "Out of difficulties grow miracles.", author: "Jean de la Bruyère" },
  { text: "Smooth seas do not make skillful sailors.", author: "African Proverb" },
  { text: "The gem cannot be polished without friction, nor man perfected without trials.", author: "Confucius" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Fortune favors the prepared mind.", author: "Louis Pasteur" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "Plans are worthless, but planning is everything.", author: "Dwight D. Eisenhower" },
  { text: "If you fail to plan, you plan to fail.", author: "Benjamin Franklin" },
  { text: "Vision without execution is just hallucination.", author: "Thomas Edison" },
  { text: "Ideas are easy. Implementation is hard.", author: "Guy Kawasaki" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
  { text: "The price of success is hard work, dedication to the job at hand.", author: "Vince Lombardi" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "We are what we repeatedly do; excellence is, then, not an act, but a habit.", author: "Will Durant" },
  { text: "Good habits formed at youth make all the difference.", author: "Aristotle" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you should try to be better than is who you were yesterday.", author: "Unknown" },
  { text: "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", author: "Mother Teresa" },
  { text: "Today is the day to start being who you want to be.", author: "Unknown" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Every morning is a fresh beginning.", author: "Unknown" },
  { text: "Today's accomplishments were yesterday's impossibilities.", author: "Robert H. Schuller" },
  { text: "A river cuts through rock not because of its power, but its persistence.", author: "Jim Watkins" },
  { text: "Slow and steady wins the race.", author: "Aesop" },
  { text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson" },
  { text: "Never confuse a single defeat with a final defeat.", author: "F. Scott Fitzgerald" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "Pressure is a privilege.", author: "Billie Jean King" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "When you feel like quitting, think about why you started.", author: "Unknown" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Sometimes later becomes never. Do it now.", author: "Unknown" },
  { text: "You don't need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
];

export function getDailyQuote(): { text: string; author: string } {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000);
  const index = dayOfYear % motivationalQuotes.length;
  return motivationalQuotes[index];
}

export function getRandomQuote(): { text: string; author: string } {
  return motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
}
